### PR TITLE
using production react

### PR DESCRIPTION
**Pull request by gregology**
I noticed this gem is using development react which is giving me this error

image

```
This page is using the development build of React. 🚧

Note that the development build is not suitable for production. 
Make sure to use the production build before deployment.

Open the developer tools, and the React tab will appear to the right.
```

Is there a reason to use development react instead of production in this instance? If not, here's a quick PR to update it to the production [0.16.0](https://github.com/facebook/react/releases/tag/v16.6.0) release.
Cheers Team!

### CODE REVIEW

**Comment by gregology** [comment]
Hey @rmosolgo, maybe you have some insight into this? Cheers Mate!

**Comment by rmosolgo** [comment]
Hey! Sorry about this issue. There's no good reason to use the development version, but I think we need to update the build scripts too: 

https://github.com/rmosolgo/graphiql-rails/blob/master/Rakefile#L14

That script bumps the graphiql version and its dependencies automatically. I think we should that _too_, or else the next update will put the development version in place 😖 . Want to give it a try?

**Comment by gregology** [comment]
@rmosolgo, neat rake task! Done, do you want me to squash?

**Comment by rmosolgo** [comment]
Awesome, thanks!

**Comment by rmosolgo** [comment]
🚢  in `1.7.0`!

**Pull request merged**
