### PR TITLE
Add nonce to javascript_include_tag

### PR DESCRIPTION
**Pull request by bodhish**

### CODE REVIEW

**Comment by stanhu** [comment]
This is much needed to prevent inline JavaScript from being blocked from Content Security Policy headers, since Rails 5 now supports nonce-based CSP headers. @rmosolgo Would you mind merging this and release a new version?

**Comment by stanhu** [comment]
Actually, this probably should be a configurable parameter in `GraphiQL::Rails.config`.

**Comment by connorshea** [comment]
I'd also very much appreciate this!

**Comment by seanarnold** [comment]
@rmosolgo We're waiting on this to get merged before we can upgrade. Would you mind taking a look at this?

**Comment by rmosolgo** [comment]
Thanks for the fix here!

**Pull request merged**
