### PR TITLE
Update engine to precompile graphiql assets

### PR DESCRIPTION
**Pull request by justinlang**
Fix for https://github.com/rmosolgo/graphiql-rails/issues/75

This is my first PR against an open-source project.  I'm not sure if there's a better way to address this issue but this seems to work.  Happy to get any feedback or iterate on this.  I didn't see guidelines for contributing so please let me know if I can make this PR better!

### CODE REVIEW

**Comment by wesleyjellis** [comment]
I can confirm this works on https://github.com/wesleyjellis/sprockets_graphql/tree/precompile

**Comment by AlexVPopov** [comment]
Hello Robert @rmosolgo :) I can confirm that the provided fix indeed does the job and is also the expected way to go (at least according to the [Rails Guides](https://guides.rubyonrails.org/engines.html#separate-assets-precompiling)). Do you mind reviewing this and in case you agree with it, also merging and releasing it? I'm in the process of updating the [How to GraphQL Ruby tutorial](https://www.howtographql.com/graphql-ruby/0-introduction/) for Rails 6 and I'd like to avoid adding an instruction for the users to add the graphiql-assets in the manifest.js of their application.

**Comment by erichmachado** [comment]
Hi @rmosolgo. Do you have plans to release a new version of this gem soon? It would be great if this PR could be merged into it.

**Comment by rmosolgo** [comment]
Sorry for the delay, and thanks for the fix! I'll cut a new release later today.

**Pull request merged**
